networks:
  1panel-network:
    external: true
services:
  mysql:
    command:
      - --mysql-native-password=on
    container_name: mysql842
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048MB
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:8.4.2
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
    ports:
      - 3306:3306
    restart: always
    volumes:
      - /mnt/d/mysql/842/log:/var/log/mysql
